---
adapter: { name: xdotool } # default value
keymap:
  AUDIO:
  BLUE:
  BRIGHTNESSDOWN:
  BRIGHTNESSUP:
  CAMERA:
  CHANNELDOWN:
  CHANNELUP:
  DELETE: BackSpace
  DOWN: Down
  DVD:
  EJECTCD:
  ENTER: KP_Enter
  EPG: e
  EXIT: XF86Away
  FASTFORWARD: XF86AudioForward
  GREEN:
  INFO:
  LANGUAGE:
  LEFT: Left
  MEDIA:
  MESSENGER:
  MODE:
  MUTE: XF86AudioMute
  NEXT: XF86AudioNext
  NUMERIC_0: 0
  NUMERIC_1: 1
  NUMERIC_2: 2
  NUMERIC_3: 3
  NUMERIC_4: 4
  NUMERIC_5: 5
  NUMERIC_6: 6
  NUMERIC_7: 7
  NUMERIC_8: 8
  NUMERIC_9: 9
  NUMERIC_POUND: null
  NUMERIC_STAR: null
  OK: XF86Book
  PAUSE: XF86AudioPause
  PLAY: XF86AudioPlay
  PLAYER:
  PLAYPAUSE:
  POWER2: XF86PowerOff
  PRESENTATION:
  PREVIOUS: XF86AudioPrev
  PRINT:
  PVR:
  RADIO:
  RECORD: XF86AudioRecord
  RED:
  REWIND: XF86AudioRewind
  RIGHT: Right
  SLEEP:
  STOP: XF86AudioStop
  SUBTITLE:
  TITLE:
  TUNER:
  TV:
  UP: Up
  VIDEO:
  VOLUMEDOWN: XF86AudioLowerVolume
  VOLUMEUP: XF86AudioRaiseVolume
  YELLOW:
  ZOOM: