---
x-defaults: &defaults
  dump: true
  logger: true # default: true
# adapters -------------------------------------------------------------
dummy:
  <<: *defaults
xdotool:
  keymap: 'config/keymap.yml'
  options: ["--clearmodifiers"]
  <<: *defaults